name: Merge Upstream Changes

on:
  schedule:
    - cron: '0 2 * * *' # Runs daily at 2:00 AM UTC (adjust as needed)
  workflow_dispatch: # Allows manual trigger

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v3
        with:
          # Check out your fork repository
          repository: zaarrg/stremio-web-shell-fixes
          ref: development

      - name: Add upstream remote
        run: git remote add upstream https://github.com/Stremio/stremio-web.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream/development into your fork's main
        run: |
          git config --global user.name 'Zaarrg'
          git config --global user.email 'Zaarrg@users.noreply.github.com'
          
          git merge upstream/development --allow-unrelated-histories
          git push origin development
        env:
          # If needed, use your PAT if GITHUB_TOKEN is insufficient:
          # GIT_AUTH_TOKEN: ${{ secrets.UPSTREAM_PAT }}
          # For pushes using PAT:
          # git push https://${GIT_AUTH_TOKEN}@github.com/your-username/your-forked-repo.git main
          GIT_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
